Update readme.md
vircadia/vircadia-builder pull request #18
Opened 2020-07-20 20:39 UTC by kasenvr

- Updates link to pull repo
- Clarifies AppImage building

2020-07-20 20:55 UTC, daleglass commented on README.md
> +    git clone https://github.com/kasenvr/vircadia-builder.git
Hmm.... this doesn't make a whole lot of sense in my personal repository

2020-08-06 22:15 UTC, JulianGro commented on README.md
> +You can  create an AppImage using the `--make-appimage` argument.
```suggestion
You can create an AppImage using the `--make-appimage` argument.
```
No need for double space.  ;)

2020-08-06 22:22 UTC, kasenvr commented on README.md
> +    git clone https://github.com/kasenvr/vircadia-builder.git
Agreed, I just have to..... make a branch or something. :D

2021-06-18 01:10 UTC, JulianGro requested changes

2021-06-18 01:10 UTC, JulianGro commented on README.md
> +To update Node.js, manually add the 16.x repository as shown [here](https://github.com/nodesource/distributions)
Adding a repository like this is going to break dependencies. Especially since they don't follow the same rules as the official repositories do. They put NPM into the nodejs package, which will break stuff. For example the current version of vircadia-builder will either run into an error, or just nuke that updated nodejs package.

We should just upgrade NPM via NPM like everyone else. E.g. `npm install -g npm@5.1.0`

2021-07-15 21:44 UTC, closed without merging

2021-07-15 21:44 UTC, digisomni commented on README.md
> +To update Node.js, manually add the 16.x repository as shown [here](https://github.com/nodesource/distributions)
If that works then I should open a new PR to show that. :)